services:
  - type: web
    plan: free
    name: LanguageLearn
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn LanguageLearn.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: LanguageLearn
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4