# Generated by Django 5.0.4 on 2024-05-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocab",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
